// Auto-generated image configuration
// Generated by scan_images.py

const imageFiles = {
    "AcanthosisNigricans": [
        "3361535.jpg",
        "3361998.jpg",
        "363080.jpg",
        "40703.jpg",
        "40813.jpg",
        "40895.jpg",
        "41024.jpg"
    ],
    "AcneVulgaris": [
        "2106161.jpg",
        "3267893.jpg",
        "3272505.jpg",
        "3273422.jpg",
        "396782.jpg",
        "397165.jpg",
        "519488.jpg",
        "927671.jpg",
        "929214.jpg"
    ],
    "ActinicKeratosis": [
        "3311616.jpg",
        "3311772.jpg",
        "3312200.jpg",
        "3312587.jpg",
        "3312846.jpg",
        "5453685.jpg",
        "82140.jpg",
        "860937.jpg"
    ],
    "AllergicContactDermatitis": [
        "172031.jpg",
        "307504.jpg",
        "559015.jpg",
        "559688.jpg",
        "561135.jpg",
        "568755.jpg",
        "574090.jpg",
        "575496.jpg",
        "577037.jpg"
    ],
    "AtopicDermatitis": [
        "214627.jpg",
        "2561917.jpg",
        "2796722.jpg",
        "3880375.jpg",
        "3880438.jpg",
        "543820.jpg",
        "544569.jpg",
        "5805667.jpg"
    ],
    "BCC": [
        "394438.jpg",
        "394808.jpg",
        "548412.jpg",
        "8213860.jpg",
        "82943.jpg"
    ],
    "BullousPemphigoid": [
        "1676791.jpg",
        "1677181.jpg",
        "1677223.jpg",
        "226291.jpg",
        "770305.jpg"
    ],
    "Cellulitis": [
        "2929664.jpg",
        "3025050.jpg",
        "3352571.jpg",
        "424603.jpg",
        "424717.jpg",
        "4283822.jpg",
        "453515.jpg",
        "5299199.jpg"
    ],
    "DermatitisHerpetiformis": [
        "146935.jpg",
        "2652485.jpg",
        "2652863.jpg",
        "2664056.jpg",
        "4795391.jpg",
        "587840.jpg",
        "588218.jpg",
        "588479.jpg",
        "7180352.jpg"
    ],
    "Drug-induced photosensitivity": [
        "2198507.jpg",
        "220003.jpg",
        "2202403.jpg",
        "2884425.jpg",
        "374069.jpg",
        "374263.jpg",
        "374940.jpg",
        "374982.jpg"
    ],
    "DrugInducedHypersensitivitySyndrome (DIHS)": [
        "1094591.jpg",
        "1094720.jpg",
        "1094838.jpg",
        "1095029.jpg",
        "3566.jpg",
        "3619.jpg",
        "3727.jpg",
        "4785850.jpg",
        "9808129.jpg"
    ],
    "Erysipelas": [
        "1822243.jpg",
        "1822463.jpg",
        "1822521.jpg",
        "2766783.jpg",
        "280184.jpg",
        "280199.jpg",
        "47546.jpg"
    ],
    "ErythemaMultiforme": [
        "132338.jpg",
        "30307.jpg",
        "609983.jpg",
        "610372.jpg",
        "611620.jpg",
        "612095.jpg"
    ],
    "ErythemaNodosum": [
        "46132.jpg",
        "4628737.jpg",
        "4628892.jpg",
        "5409791.jpg",
        "612608.jpg",
        "7801153.jpg",
        "8605691.jpg"
    ],
    "HidradenitisSuppurativa": [
        "2107939.jpg",
        "3724292.jpg",
        "3724486.jpg",
        "4032732.jpg",
        "449293.jpg",
        "449385.jpg",
        "5351423.jpg"
    ],
    "HSV": [
        "176721.jpg",
        "248988.jpg",
        "277068.jpg",
        "2837065.jpg",
        "2850295.jpg",
        "324177.jpg",
        "3628861.jpg",
        "429945.jpg"
    ],
    "IchthyosisVulgaris": [
        "3017471.jpg",
        "4651596.jpg",
        "4651675.jpg",
        "4651897.jpg",
        "657795.jpg",
        "657992.jpg",
        "6762930.jpg"
    ],
    "Impetigo": [
        "188415.jpg",
        "3432512.jpg",
        "3433472.jpg",
        "4983657.jpg",
        "5301859.jpg",
        "557633.jpg"
    ],
    "Langerhans": [
        "417487.jpg",
        "417661.jpg",
        "417711.jpg",
        "417872.jpg",
        "418096.jpg",
        "648627.jpg"
    ],
    "LichenPlanus": [
        "21091.jpg",
        "21134.jpg",
        "21187.jpg",
        "239543.jpg",
        "2727855.jpg",
        "303516.jpg",
        "3655874.jpg",
        "682568.jpg",
        "682651.jpg",
        "683230.jpg",
        "683264.jpg",
        "684835.jpg"
    ],
    "Mastocytosis-UP": [
        "1315207.jpg",
        "1316421.jpg",
        "1318044.jpg",
        "1319936.jpg",
        "1322048.jpg",
        "174492.jpg",
        "2663241.jpg",
        "801499.jpg",
        "881587.jpg"
    ],
    "Melanoma": [
        "162012.jpg",
        "207449.jpg",
        "732416.jpg",
        "733445.jpg"
    ],
    "Molluscum": [
        "3688969.jpg",
        "420795.jpg",
        "420956.jpg",
        "447331.jpg",
        "514304.jpg",
        "515292.jpg",
        "517376.jpg",
        "76426.jpg"
    ],
    "Mpox": [
        "10514578.jpg",
        "10514693.jpg",
        "10514800.jpg",
        "10514844.jpg",
        "10519487.jpg",
        "10519750.jpg",
        "10519921.jpg"
    ],
    "PemphigusVulgaris": [
        "174456.jpg",
        "444828.jpg",
        "758215.jpg",
        "758273.jpg",
        "759030.jpg",
        "761635.jpg",
        "765947.jpg"
    ],
    "PolymorphousLightEruption (PMLE)": [
        "2865564.jpg",
        "3740515.jpg",
        "6342.jpg",
        "6438300.jpg",
        "6438391.jpg",
        "6438590.jpg",
        "6439394.jpg",
        "766208.jpg",
        "7674152.jpg"
    ],
    "Psoriasis": [
        "10145530.jpg",
        "1180928.jpg",
        "3018431.jpg",
        "496949.jpg",
        "498315.jpg",
        "5184399.jpg",
        "9674605.jpg",
        "9674751.jpg",
        "9827027.jpg"
    ],
    "Rosacea": [
        "114944.jpg",
        "177955.jpg",
        "3287352.jpg",
        "3289156.jpg",
        "521827.jpg",
        "522438.jpg",
        "585948.jpg",
        "585989.jpg",
        "6615056.jpg"
    ],
    "SCC": [
        "1049096.jpg",
        "161783.jpg",
        "3678207.jpg",
        "3680840.jpg",
        "3680923.jpg",
        "432782.jpg",
        "844848.jpg"
    ],
    "SeborrheicKeratosis": [
        "2328487.jpg",
        "2653300.jpg",
        "323909.jpg",
        "324608.jpg",
        "661930.jpg",
        "67971.jpg",
        "68074.jpg",
        "76731.jpg",
        "835262.jpg"
    ],
    "SJS-TEN": [
        "132144.jpg",
        "1398629.jpg",
        "1518457.jpg",
        "3045632.jpg",
        "3045701.jpg",
        "3048817.jpg",
        "335677.jpg",
        "4564188.jpg",
        "4564273.jpg",
        "609344.jpg",
        "616021.jpg"
    ],
    "Urticaria": [
        "1251754.jpg",
        "174617.jpg",
        "29375.jpg",
        "320576.jpg",
        "375290.jpg",
        "375759.jpg",
        "376064.jpg",
        "376181.jpg",
        "6888012.jpg",
        "6888075.jpg",
        "7814846.jpg"
    ],
    "VaricellaZoster": [
        "117695.jpg",
        "120767.jpg",
        "128116.jpg",
        "2351168.jpg",
        "2826560.jpg",
        "2836682.jpg",
        "2942364.jpg",
        "645440.jpg"
    ]
};
