import os
import json

# Base directory containing all condition folders
DERM_DIR = './DERM'

# Output JavaScript file
OUTPUT_FILE = 'imageConfig.js'

def scan_images():
    """Scan all folders in DERM directory and find .jpg files"""
    image_files = {}
    
    # Check if DERM directory exists
    if not os.path.exists(DERM_DIR):
        print(f"Error: {DERM_DIR} directory not found!")
        return image_files
    
    # Scan each subdirectory
    for folder_name in os.listdir(DERM_DIR):
        folder_path = os.path.join(DERM_DIR, folder_name)
        
        # Skip if not a directory
        if not os.path.isdir(folder_path):
            continue
        
        # Find all .jpg files in this folder
        jpg_files = [f for f in os.listdir(folder_path) 
                     if f.lower().endswith('.jpg')]
        
        # Sort filenames for consistency
        jpg_files.sort()
        
        # Add to dictionary
        image_files[folder_name] = jpg_files
        
        print(f"Found {len(jpg_files)} images in {folder_name}")
    
    return image_files

def generate_js_config(image_files):
    """Generate JavaScript configuration file"""
    js_content = "// Auto-generated image configuration\n"
    js_content += "// Generated by scan_images.py\n\n"
    js_content += "const imageFiles = "
    js_content += json.dumps(image_files, indent=4)
    js_content += ";\n"
    
    with open(OUTPUT_FILE, 'w') as f:
        f.write(js_content)
    
    print(f"\nGenerated {OUTPUT_FILE} successfully!")

if __name__ == '__main__':
    print("Scanning DERM directory for images...\n")
    images = scan_images()
    
    if images:
        generate_js_config(images)
        print(f"\nTotal conditions scanned: {len(images)}")
        print(f"Total images found: {sum(len(v) for v in images.values())}")
    else:
        print("No images found!")